Repository AI-Course-Team-4/KetoHelper, pull requests merged in 2025-10, with the labels that each got.

#280 Release: dev → main
  .gitignore
  backend/app/agents/meal_planner.py
  backend/app/core/orchestrator.py
  backend/app/domains/meal/api/plans.py
  backend/app/tools/meal/response_formatter.py
  backend/app/tools/shared/date_parser.py
  backend/app/tools/shared/hybrid_search.py
  backend/app/tools/shared/profile_tool.py
  frontend/src/components/Header.tsx
  frontend/src/components/Navigation.tsx
  frontend/src/components/chatPage/ActiveWelcome.tsx
  frontend/src/components/chatPage/ChatPage.tsx
  frontend/src/components/chatPage/EmptyWelcome.tsx
  frontend/src/components/chatPage/MessageInput.tsx
  frontend/src/components/chatPage/MessageItem.tsx
  frontend/src/components/chatPage/MessageList.tsx
  frontend/src/components/chatPage/QuickActions.tsx
  frontend/src/components/chatPage/ThreadSidebar.tsx
  frontend/src/components/chatPage/hooks/useChatLogic.ts
  frontend/src/components/chatPage/hooks/useMessageHandlers.ts
  frontend/src/components/chatPage/hooks/useThreadHandlers.ts
  frontend/src/components/chatPage/hooks/useTypingAnimation.ts
  frontend/src/components/chatPage/index.ts
  frontend/src/contexts/AuthContext.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/index.css
  frontend/src/lib/axiosClient.ts
  frontend/src/main.tsx
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/ChatPage.tsx
  frontend/src/services/AuthService.ts
  frontend/src/store/chatStore.ts
Labels: deploy

#282 frontend_jch_calandar
  frontend/src/pages/CalendarPage.tsx
Labels: frontend

#283 chan/recipe_validation_v3
  backend/app/core/config.py
  backend/app/core/intent_classifier.py
  backend/app/core/orchestrator.py
  backend/app/domains/chat/api/chat.py
  backend/app/prompts/chat/intent_classification.py
  intent_classifier_v2.py
  place_search_agent.py
  scripts/.tmp_view
  scripts/eval_routing.py
Labels: backend

#284 fix/soohwan-chatpage-bug
  frontend/src/components/chatPage/ChatPage.tsx
  frontend/src/components/chatPage/hooks/useChatLogic.ts
  frontend/src/components/chatPage/hooks/useThreadHandlers.ts
Labels: bug, frontend

#289 Release: dev → main
  frontend/src/store/chatStore.ts
Labels: deploy

#299 Release: dev → main
  frontend/src/components/chatPage/hooks/useChatLogic.ts
  frontend/src/components/chatPage/hooks/useMessageHandlers.ts
Labels: deploy

#301 frontend_jch_calandar
  frontend/src/components/DateDetailModal.tsx
  frontend/src/components/MealDetailModal.tsx
  frontend/src/components/calendarPage/CalendarDay.tsx
Labels: frontend

#305 Release: dev → main
  frontend/src/components/chatPage/hooks/useChatLogic.ts
Labels: deploy

#307 chan/recipe_validation_v3
  .gitignore
  backend/app/agents/meal_planner.py
  backend/app/agents/place_search_agent.py
  backend/app/core/database.py
  backend/app/core/orchestrator.py
  backend/app/domains/restaurant/api/places.py
  backend/app/prompts/restaurant/chan_recommendation.py
  backend/app/prompts/restaurant/chan_search_improvement.py
  backend/app/shared/models/schemas.py
  backend/app/tools/restaurant/place_search.py
  backend/app/tools/restaurant/restaurant_hybrid_search.py
Labels: backend

#308 fix/soohwan-logout-bug
  frontend/src/contexts/AuthContext.tsx
  frontend/src/services/AuthService.ts
Labels: bug

#309 Release: dev → main
  .gitignore
  backend/app/agents/meal_planner.py
  backend/app/agents/place_search_agent.py
  backend/app/core/database.py
  backend/app/core/orchestrator.py
  backend/app/domains/restaurant/api/places.py
  backend/app/prompts/restaurant/chan_recommendation.py
  backend/app/prompts/restaurant/chan_search_improvement.py
  backend/app/shared/models/schemas.py
  backend/app/tools/restaurant/place_search.py
  backend/app/tools/restaurant/restaurant_hybrid_search.py
  frontend/src/contexts/AuthContext.tsx
  frontend/src/services/AuthService.ts
Labels: deploy

#315 Release: dev → main
  frontend/src/components/Header.tsx
  frontend/src/components/chatPage/hooks/useMessageHandlers.ts
  frontend/src/contexts/AuthContext.tsx
  frontend/src/pages/ProfilePage.tsx
  frontend/src/services/AuthService.ts
Labels: deploy

#318 refactor/soohwan-chatPage
  frontend/src/components/chatPage/ChatPage.tsx
  frontend/src/components/chatPage/MessageList.tsx
  frontend/src/components/chatPage/hooks/useChatLogic.ts
  frontend/src/components/chatPage/hooks/useMessageHandlers.ts
Labels: refactor

#319 Release: dev → main
  backend/app/agents/place_search_agent.py
  backend/app/prompts/restaurant/chan_recommendation.py
  backend/app/prompts/restaurant/chan_search_improvement.py
  backend/app/prompts/restaurant/recommendation.py
  backend/config/personal_config.py
  frontend/src/components/chatPage/ChatPage.tsx
  frontend/src/components/chatPage/MessageList.tsx
  frontend/src/components/chatPage/hooks/useChatLogic.ts
  frontend/src/components/chatPage/hooks/useMessageHandlers.ts
Labels: deploy

#322 chan/model_test_v5
  LLM_Switch_Factory_PRD_v1.0.md
  backend/app/agents/chat_agent.py
  backend/app/agents/meal_planner.py
  backend/app/agents/place_search_agent.py
  backend/app/core/config.py
  backend/app/core/intent_classifier.py
  backend/app/core/llm_factory.py
  backend/app/core/orchestrator.py
  backend/app/prompts/meal/recipe_response.py
  backend/app/prompts/meal/single_recipe.py
  backend/env.example
  scripts/test_chat_performance.py
  scripts/test_meal_plan_performance.py
  scripts/test_meal_save_performance.py
  scripts/test_recipe_performance.py
  scripts/test_restaurant_performance.py
Labels: backend

#325 fix/soohwan-chatpage-bug
  frontend/src/components/chatPage/ChatPage.tsx
  frontend/src/components/chatPage/MessageItem.tsx
  frontend/src/components/chatPage/MessageList.tsx
Labels: bug

#329 refactor/chatPage-markdown
  backend/app/main.py
  backend/package-lock.json
  backend/requirements.txt
  backend/runtime.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/chatPage/MessageItem.tsx
  frontend/src/index.css
Labels: refactor

#330 Release: dev → main
  backend/app/main.py
  backend/package-lock.json
  backend/requirements.txt
  backend/runtime.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/chatPage/MessageItem.tsx
  frontend/src/index.css
Labels: deploy

#333 feature/weight-config
  backend/WEIGHT_CONFIG_GUIDE.md
  backend/WEIGHT_SYSTEM_README.md
  backend/app/core/weight_config.py
  backend/app/prompts/meal/soohwan_generation.py
  backend/app/prompts/meal/soohwan_structure.py
  backend/config/weight_configs/__init__.py
  backend/config/weight_configs/jihyun.py
  backend/config/weight_configs/minseok.py
  backend/config/weight_configs/soohwan.py
  backend/run_server_enhanced.py
Labels: setting

#334 feature/soo-recipe-search
  backend/app/agents/meal_planner.py
Labels: feature, backend

#343 Release: dev → main
  backend/app/agents/meal_planner.py
  backend/app/core/orchestrator.py
  backend/app/prompts/MIGRATION_GUIDE.md
  backend/app/prompts/QUICK_REFERENCE.md
  backend/app/prompts/README.md
  backend/app/prompts/TEAM_GUIDE.md
  backend/app/prompts/chat/fallback.py
  backend/app/prompts/chat/general_chat.py
  backend/app/prompts/chat/response_generation.py
  backend/app/prompts/examples/example_usage.py
  backend/app/prompts/meal/recipe_response.py
  backend/app/prompts/restaurant/search_failure.py
  backend/app/prompts/shared/README.md
  backend/app/prompts/shared/__init__.py
  backend/app/prompts/shared/common_templates.py
  backend/app/tools/shared/hybrid_search.py
  backend/app/tools/shared/profile_tool.py
  frontend/src/pages/ProfilePage.tsx
Labels: deploy
