Repository AI-Course-Team-4/KetoHelper, pull requests merged in 2025-09, with the labels that each got.

#2 Readme에 불필요한 내용 수정
  CONTRIBUTING.md
  README.md
Labels: setting

#4 dev내용 main으로 push하기 위한 pr
  .github/ISSUE_TEMPLATE/issue template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  PRD_COMPLETE.md
  README.md
  env.example
  frontend/src/App.tsx
  frontend/src/pages/Test.tsx
Labels: setting

#5 Update pull_request_template.md
  .github/pull_request_template.md
Labels: setting

#6 test: 테스트
  CONTRIBUTING.md
Labels: setting

#9 dev2main의 alias 변경
  CONTRIBUTING.md
Labels: setting

#10 Update pull_request_template.md
  .github/pull_request_template.md
Labels: setting

#15 Release: dev → main
  CONTRIBUTING.md
  frontend/src/pages/Test.tsx
Labels: setting

#16 setting
  CONTRIBUTING.md
Labels: setting

#23 Update issue templates
  .github/ISSUE_TEMPLATE/이슈-템플릿.md
Labels: setting

#28 setting
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: setting

#32 feature/se
  backend/app/api/v1/endpoints/auth.py
  frontend/src/pages/SettingsPage.tsx
  frontend/src/services/api.ts
  frontend/src/services/authService.ts
  frontend/src/store/authStore.ts
Labels: feature

#35 setting
  .github/ISSUE_TEMPLATE/config.yml
  backend/package-lock.json
Labels: setting

#36 setting
  .github/ISSUE_TEMPLATE/config.yml
Labels: setting

#41 setting
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: setting

#50 setting
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: setting

#54 feature/se
  frontend/src/pages/KakaoMap.tsx
  frontend/src/pages/RestaurantsPage.tsx
  frontend/src/services/authService.ts
  frontend/src/vite-env.d.ts
Labels: page

#69 feature/se-restaurantPage
  frontend/src/components/KakaoMap.tsx
  frontend/src/components/RestaurantCard.tsx
  frontend/src/components/RestaurantDetail.tsx
  frontend/src/pages/RestaurantsPage.tsx
Labels: page

#80 setting
  README.md
Labels: setting

#86 feature/se-restaurantPage
  frontend/src/components/KakaoMap.tsx
  frontend/src/components/RestaurantCard.tsx
  frontend/src/components/RestaurantDetail.tsx
  frontend/src/pages/RestaurantsPage.tsx
Labels: page

#90 setting-soohwan
  backend/.env
  backend/chroma/706f16d2-fcb6-4079-946c-f5da32ff69a2/data_level0.bin
  backend/chroma/706f16d2-fcb6-4079-946c-f5da32ff69a2/header.bin
  backend/chroma/706f16d2-fcb6-4079-946c-f5da32ff69a2/length.bin
  backend/chroma/706f16d2-fcb6-4079-946c-f5da32ff69a2/link_lists.bin
  backend/chroma/chroma.sqlite3
Labels: setting

#94 dev 내용을 에러 없이 수정한 dev-ready 브랜치 내용을 dev로 pr
  backend/app/api/__pycache__/__init__.cpython-312.pyc
  backend/app/core/__pycache__/config.cpython-312.pyc
  backend/app/core/__pycache__/database.cpython-312.pyc
  backend/app/core/config.py
  backend/requirements.txt
  package-lock.json
Labels: setting

#97 Update issue templates
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: setting

#98 soohwan/requirements-optimization
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: setting

#99 Update issue_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: setting

#100 Update requirements.txt
  backend/requirements.txt
Labels: setting

#101 Update README.md
  README.md
Labels: setting

#102 feature/se
  .gitignore
  frontend/src/pages/KakaoMap.tsx
  frontend/src/pages/MapPage.tsx
  frontend/src/types/kakao.d.ts
  frontend/src/vite-env.d.ts
Labels: setting, page

#106 frontend_jch
  .gitignore
  frontend/src/components/MealModal.tsx
  frontend/src/data/ketoMeals.ts
  frontend/src/index.css
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/ChatPage.tsx
Labels: page, feature

#108 frontend_jch_calandar
  frontend/src/components/MealModal.tsx
  frontend/src/pages/CalendarPage.tsx
Labels: frontend

#109 feature/se-socialLogin-fix
  frontend/src/components/LoginModal.tsx
  frontend/src/pages/NaverCallback.tsx
Labels: bug, feature, frontend

#123 full_sh/deploy_setting
  backend/app/main.py
  backend/requirements.txt
  backend/runtime.txt
Labels: setting

#128 Sync main → dev
  backend/requirements.txt
Labels: setting

#132 setting-soohwan
  backend/app/main.py
Labels: setting

#136 full_sh/deploy-setting
  frontend/src/hooks/useApi.ts
Labels: setting

#137 setting-soohwan
  CONTRIBUTING.md
Labels: setting

#139 Release: dev → main
  CONTRIBUTING.md
  backend/app/main.py
  frontend/src/hooks/useApi.ts
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/SubscribePage.tsx
Labels: setting

#141 feature/se-mainPage-design
  frontend/src/pages/MainPage.tsx
Labels: page, frontend

#145 feature/se-restaurantPage
  frontend/src/pages/KakaoMap.tsx
  frontend/src/pages/KetoRestaurant.tsx
  frontend/src/pages/MapPage.tsx
Labels: page, frontend

#147 full_sh/deploy_setting
  backend/app/main.py
Labels: setting

#148 Release: dev → main
  backend/app/main.py
  frontend/src/hooks/useApi.ts
  frontend/src/pages/KakaoMap.tsx
  frontend/src/pages/KetoRestaurant.tsx
  frontend/src/pages/MapPage.tsx
Labels: setting

#157 Release: dev → main
  backend/app/core/database.py
  backend/app/shared/api/auth.py
  frontend/src/components/LoginModal.tsx
  frontend/src/public/logos/google.svg
  frontend/src/public/logos/kakaotalk.svg
  frontend/vercel.json
Labels: setting

#175 full_sh/deploy-setting
  frontend/vercel.json
Labels: setting

#184 feature/se-restaurantPage
  frontend/src/pages/KakaoMap.tsx
  frontend/src/pages/MapPage.tsx
Labels: page, frontend

#185 chan/exception
  1_개월_완성_대화형_키토_식단_식당_추천_웹앱_실행_가이드_학생팀_실전판.md
  MEAL_FEATURES_COMPLETED.md
  MEAL_INTEGRATION_UPDATED.md
  backend/app/core/guard_middleware.py
  backend/app/core/guard_service.py
  backend/app/domains/admin/__init__.py
  backend/app/domains/admin/api/__init__.py
  backend/app/domains/admin/api/metrics.py
  backend/app/main.py
  backend/app/shared/guards/__init__.py
  backend/app/shared/guards/validators.py
  backend/app/shared/models/guard_models.py
  backend/app/tools/restaurant/place_search.py
  backend/requirements.txt
  frontend/src/pages/MapPage.tsx
  test_map.html
Labels: backend

#188 feature/soo-hybrid-intent
  backend/app/core/intent_classifier.py
  backend/app/core/orchestrator.py
  backend/app/prompts/chat/intent_classification.py
Labels: feature, backend, refactor

#193 feature/se-restaurantPage
  frontend/src/components/LoginModal.tsx
  frontend/src/components/PlaceCard.tsx
  frontend/src/pages/ChatPage.tsx
  frontend/src/pages/KakaoMap.tsx
Labels: page, frontend

#194 feature/sh-profile
  backend/app/shared/api/auth.py
  docs/add_social_login_columns.sql
  docs/social_login_provider_fix_pr.md
Labels: setting, backend

#202 Release: dev → main
  PRD 키토 코치 채팅 연속성 및 비로그인 사용자 지원 기능 .md
  backend/app/core/orchestrator.py
  backend/app/domains/chat/api/chat.py
  backend/app/shared/api/auth.py
  frontend/src/index.css
  frontend/src/pages/CalendarPage.tsx
  챗봇_대화_저장_MVP_가이드.md
Labels: backend

#206 Release: dev → main
  frontend/src/components/LoginModal.tsx
Labels: deploy

#208 fix/soohwan
  frontend/src/components/LoginModal.tsx
  frontend/src/pages/NaverCallback.tsx
Labels: bug, frontend

#211 fix/soohwan
  frontend/src/components/LoginModal.tsx
  frontend/src/pages/NaverCallback.tsx
Labels: frontend

#215 feature/soo-calendar-save
  backend/app/core/database.py
  backend/app/domains/meal/api/plans.py
  backend/app/shared/models/database_models.py
  backend/app/shared/models/schemas.py
  backend/app/tools/restaurant/place_search.py
  frontend/src/data/ketoMeals.ts
  frontend/src/hooks/useApi.ts
  frontend/src/lib/dateParser.ts
  frontend/src/lib/mealService.ts
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/ChatPage.tsx
Labels: feature, backend, refactor

#218 fix/soohwan
  backend/app/shared/api/auth.py
  frontend/src/components/LoginModal.tsx
Labels: frontend

#220 Release: dev → main
  backend/app/core/database.py
  backend/app/domains/meal/api/plans.py
  backend/app/shared/api/auth.py
  backend/app/shared/models/database_models.py
  backend/app/shared/models/schemas.py
  backend/app/tools/restaurant/place_search.py
  frontend/src/components/LoginModal.tsx
  frontend/src/data/ketoMeals.ts
  frontend/src/hooks/useApi.ts
  frontend/src/lib/dateParser.ts
  frontend/src/lib/mealService.ts
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/ChatPage.tsx
Labels: deploy

#222 fix/soohwan
  backend/app/shared/api/auth.py
Labels: backend, frontend

#227 fix/soohwan
  backend/app/shared/api/auth.py
Labels: backend

#235 fix/soohwan
  frontend/src/lib/axiosClient.ts
  frontend/vercel.json
Labels: bug

#237 Release: dev → main
  frontend/src/lib/axiosClient.ts
  frontend/vercel.json
Labels: deploy

#242 feature/soo-calendar-save
  backend/app/domains/chat/api/__init__.py
  backend/app/domains/chat/api/date_parser.py
  backend/app/main.py
  backend/app/tools/shared/date_parser.py
  frontend/src/hooks/useApi.ts
  frontend/src/lib/dateParser.ts
  frontend/src/pages/ChatPage.tsx
Labels: backend, refactor

#243 fix/soohwan
  backend/app/shared/api/auth.py
  backend/requirements.txt
Labels: bug

#244 Release: dev → main
  backend/app/domains/chat/api/__init__.py
  backend/app/domains/chat/api/date_parser.py
  backend/app/main.py
  backend/app/shared/api/auth.py
  backend/app/tools/shared/date_parser.py
  backend/requirements.txt
  frontend/src/hooks/useApi.ts
  frontend/src/lib/dateParser.ts
  frontend/src/pages/ChatPage.tsx
Labels: deploy

#247 fix/soohwan
  backend/app/shared/api/auth.py
Labels: bug

#248 Release: dev → main
  backend/app/core/config.py
  backend/app/shared/api/auth.py
  backend/env.example
  backend/env_template.txt
  backend/run_server.py
Labels: deploy

#251 frontend_jch_calandar
  frontend/src/components/DateDetailModal.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/ChatPage.tsx
Labels: feature, frontend

#252 refactor/soo-backend-structure
  backend/app/domains/chat/api/__init__.py
  backend/app/domains/chat/api/date_endpoints.py
  backend/app/domains/chat/api/date_parser.py
  backend/app/tools/shared/date_parser.py
Labels: backend, refactor

#253 refactor/soo-backend-structure
  backend/app/agents/meal_planner.py
  backend/app/core/intent_classifier.py
  backend/app/core/orchestrator.py
  backend/app/domains/chat/api/chat.py
  backend/app/tools/shared/date_parser.py
  frontend/src/hooks/useApi.ts
  frontend/src/pages/ChatPage.tsx
Labels: backend

#257 Release: dev → main
  backend/DEPLOYMENT.md
  backend/app/agents/meal_planner.py
  backend/app/core/intent_classifier.py
  backend/app/core/jwt_utils.py
  backend/app/core/orchestrator.py
  backend/app/domains/chat/api/__init__.py
  backend/app/domains/chat/api/chat.py
  backend/app/domains/chat/api/date_endpoints.py
  backend/app/domains/chat/api/date_parser.py
  backend/app/domains/meal/api/plans.py
  backend/app/prompts/meal/soobin_structure.py
  backend/app/shared/api/auth.py
  backend/app/tools/shared/date_parser.py
  backend/config/personal_config.py
  frontend/src/App.tsx
  frontend/src/components/DateDetailModal.tsx
  frontend/src/components/MealModal.tsx
  frontend/src/components/ProtectedRoute.tsx
  frontend/src/components/PublicOnlyRoute.tsx
  frontend/src/contexts/AuthContext.tsx
  frontend/src/hooks/useApi.ts
  frontend/src/index.css
  frontend/src/lib/axiosClient.ts
  frontend/src/lib/toast.ts
  frontend/src/main.tsx
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/ChatPage.tsx
  frontend/src/pages/MapPage.tsx
  frontend/src/services/AuthService.ts
  frontend/src/store/authStore.ts
Labels: deploy

#256 refactor/soo-backend-structure
  backend/app/core/orchestrator.py
  backend/app/domains/chat/api/__init__.py
  backend/app/main.py
  backend/app/prompts/calendar/__init__.py
  backend/app/prompts/calendar/save_confirmation.py
  backend/app/shared/api/date_endpoints.py
  backend/app/shared/utils/__init__.py
  backend/app/shared/utils/calendar_utils.py
  backend/app/tools/calendar/__init__.py
  backend/app/tools/calendar/calendar_conflict_handler.py
  backend/app/tools/calendar/calendar_saver.py
  backend/app/tools/shared/date_parser.py
  frontend/src/pages/ChatPage.tsx
  tatus --short
Labels: backend

#260 frontend_jch_calandar
  frontend/src/pages/CalendarPage.tsx
  frontend/src/pages/ChatPage.tsx
Labels: frontend

#265 feature/se-design
  frontend/src/components/Header.tsx
Labels: page, frontend

#266 chan/intent_develope
  .gitignore
  backend/app/agents/README.md
  backend/app/agents/place_search_agent.py
  backend/app/agents/restaurant_agent.py
  backend/app/core/orchestrator.py
  backend/app/prompts/chat/response_generation.py
  frontend/src/lib/axiosClient.ts
  frontend/src/pages/MapPage.tsx
  intent_classifier_v2.py
  place_search_agent.py
Labels: backend

#267 feature/sh-authn-token-system
  frontend/src/components/AuthRouteGuard.tsx
  frontend/src/services/AuthService.ts
Labels: bug, frontend

#268 Release: dev → main
  .gitignore
  backend/app/agents/README.md
  backend/app/agents/place_search_agent.py
  backend/app/agents/restaurant_agent.py
  backend/app/core/orchestrator.py
  backend/app/prompts/chat/response_generation.py
  frontend/src/components/AuthRouteGuard.tsx
  frontend/src/components/Header.tsx
  frontend/src/lib/axiosClient.ts
  frontend/src/pages/MapPage.tsx
  frontend/src/services/AuthService.ts
  intent_classifier_v2.py
  place_search_agent.py
Labels: deploy

#270 fix/soohwan-delete-useless-menu
  frontend/src/components/Navigation.tsx
Labels: frontend

#271 Release: dev → main
  frontend/src/components/Navigation.tsx
Labels: deploy

#276 fix/soo-search-logic-mealplan
  backend/app/agents/meal_planner.py
  backend/app/domains/meal/api/plans.py
  backend/app/tools/meal/response_formatter.py
Labels: bug, backend

#277 feature/se-ketoRandomTip
  .gitignore
  frontend/src/components/Navigation.tsx
Labels: page, frontend

#278 frontend_jch_calandar
  backend/app/agents/meal_planner.py
  frontend/src/hooks/useApi.ts
  frontend/src/pages/CalendarPage.tsx
Labels: backend, frontend
